---
   - name: Install and Configure Database
     yum:
       name: "{{ packages }}"
     vars:
       packages:
       - mysql-community-server
       - mysql-community-client
   - name: Start MySQL Service
     service:
       name: mysqld
       state: started
       enabled: yes

   - name: Create Application Database
     mysql_db: name= {{ db_name }} state=present

   - name: Create Database user
     mysql_user:
       name: "{{ db_user }}"
       password: "{{ db_password }}"
       priv: '*.*:ALL'
       state: present
